#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-container
        image: "{{ .Values.image.repository }}:8"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: '0.5G'
          requests:
            cpu: '0.2'
            memory: '0.10G'
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred



