 apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: petclicnic-hpa
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
   apiVersion: apps/v2
   kind: Deployment
   name: petclinic-deployment
 targetCPUUtilizationPercentage: 50
